Description: Create coach users for DevOps Girls
Parameters:
  PasswordPrefix:
    Description: Used to generate temporary password
    Type: String
    Default: Password@2019
Resources:
  DevOpsGirlsCoachGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: devops-girls-coach
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/PowerUserAccess'
  Coach01:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach01
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#01'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach02:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach02
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#02'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach03:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach03
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#03'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach04:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach04
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#04'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach05:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach05
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#05'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach06:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach06
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#06'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach07:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach07
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#07'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach08:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach08
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#08'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach09:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach09
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#09'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
  Coach10:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Coach10
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#10'
      Groups:
        - !Ref DevOpsGirlsCoachGroup
      Path: /
