Description: Create users for workshop
Parameters:
  PasswordPrefix:
    Description: Used to generate temporary password
    Type: String
    Default: Password@2018
Resources:
  WorkshopGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: workshop
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/PowerUserAccess'
  WorkshopUser01:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser01
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#01'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser02:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser02
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#02'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser03:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser03
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#03'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser04:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser04
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#04'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser05:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser05
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#05'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser06:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser06
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#06'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser07:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser07
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#07'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser08:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser08
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#08'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser09:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser09
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#09'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser10:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser10
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#10'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser11:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser11
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#11'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser12:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser12
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#12'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser13:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser13
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#13'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser14:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser14
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#14'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser15:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser15
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#15'
      Groups:
        - !Ref WorkshopGroup
      Path: /
  WorkshopUser16:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: workshopuser16
      LoginProfile:
        Password: !Join 
          - ''
          - - !Ref PasswordPrefix
            - '#16'
      Groups:
        - !Ref WorkshopGroup
      Path: /
