#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-vars

./auto/create-template $1

STACK_NAME=$(echo ${STACK_NAME:-"tw-toc-workshop-users"} | tr "A-Z" "a-z")

docker run --rm -v $PWD:/cwd \
	-e AWS_ACCOUNT \
	-e AWS_EXPIRE \
	-e AWS_EXPIRETIME \
	-e AWS_ROLE \
	-e AWS_ROLE_SESSION_NAME \
	-e AWS_SESSION_TOKEN \
	-e AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY \
	-e AWS_SECURITY_TOKEN \
	-e AWS_DEFAULT_REGION \
	"${STACKUP_IMAGE}@${STACKUP_HASH}" \
	"${STACK_NAME}" \
	up \
	--template ./aws/deployment/users/cloudformation.yml \
	--tags ./aws/deployment/users/tags.yml \
	--region ap-southeast-1
